### ISSUE TITLE
How do you manage the different colored top bars of your windows?

### ISSUE THREAD

**Issue by chopfitzroy** [NickBrisebois/dotfiles#2]
You have the blue and the red/brown title bars on different windows I have seen that on a few rices how do you pull it off?

Cheers.

**Comment by NickBrisebois** [comment]
TBH I don't know haha. I'm just using [this openbox theme](https://github.com/NickBrisebois/dotfiles/tree/master/.themes/yellow%20(copy)) that I got from a /r/unixporn thread
